[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[anexo100]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=anexo100
aors=anexo100

[anexo100]
type=auth
auth_type=userpass
password=123lab
username=anexo100

[anexo100]
type=aor
max_contacts=5

[anexo200]
type=endpoint
context=anexos
disallow=all
allow=ulaw,alaw
auth=clave200
aors=anexo200

[clave200]
type=auth
auth_type=userpass
password=123lab
username=anexo200

[anexo200]
type=aor
max_contacts=5
